apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boutique-dev

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
    target:
      kind: Deployment

images:
  - name: adservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/adservice
    newTag: v0.10.4
  - name: cartservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/cartservice
    newTag: v0.10.4
  - name: checkoutservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/checkoutservice
    newTag: v0.10.4
  - name: currencyservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/currencyservice
    newTag: v0.10.4
  - name: emailservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/emailservice
    newTag: v0.10.4
  - name: frontend
    newName: kindheart213/frontend
    newTag: <actual-tag-here>
  - name: loadgenerator
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/loadgenerator
    newTag: v0.10.4
  - name: paymentservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/paymentservice
    newTag: v0.10.4
  - name: productcatalogservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice
    newTag: v0.10.4
  - name: recommendationservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/recommendationservice
    newTag: v0.10.4
  - name: shippingservice
    newName: us-central1-docker.pkg.dev/google-samples/microservices-demo/shippingservice
    newTag: v0.10.4
