apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kenzo213/online-boutique-gitops
    targetRevision: main
    path: manifests/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: boutique-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
